/**
 * Cifra — o vocabulário. **Gerado**, não escrito à mão.
 *
 * Sai de `scripts/cifra-palavras.mjs`, que lê uma lista de frequência do
 * português (hermitdave/FrequencyWords, licença MIT, derivada de legendas do
 * OpenSubtitles) e a corta em duas. Para mexer no vocabulário, mexa no script
 * e rode-o de novo — editar este arquivo à mão perde na próxima geração.
 *
 *     node scripts/cifra-palavras.mjs
 *
 * As duas listas existem porque o jogo faz duas perguntas com exigências
 * opostas:
 *
 *   RESPOSTAS  — de onde sai a palavra do dia. Só palavra comum: obscura não é
 *                desafio, é sorteio. Corte de frequência >= 1200.
 *   EXTRAS     — só valida chute. Aceitar um vocábulo estranho que ninguém
 *                digitaria não custa nada; *recusar* palavra real quebra a
 *                confiança na regra. Corte >= 30.
 *
 * Acentuação é ignorada na comparação e só reaparece na revelação: quem sabe a
 * grafia não deve perder por não achar a tecla. Como consequência, duas
 * grafias que só diferem no acento são o *mesmo* chute — o gerador mantém a
 * mais frequente e o `?conferir` falha se alguma colisão escapar.
 */

/** Tira acento e cedilha e sobe pra maiúscula. É a forma em que o jogo compara. */
export const semAcento = (s) =>
  s.normalize('NFD').replace(/[\u0300-\u036F]/g, '').toUpperCase();

/** As palavras do dia. Curadas pelo corte de frequência e pela lista de exclusão. */
export const RESPOSTAS = `
  abram abrem abril abrir abriu abuso acaba acabe acabo acaso acesa acham
  achar achas achei achem achou ácido acima ações acres acusa adaga adams
  adega adele adeus adiar adora adoro aérea aéreo afeta afeto agido agora
  águas aguda águia aiden ainda ajuda ajude ajudo álbum alega alemã algas
  algum aliás álibi alien almas alpha altar altas altos aluna aluno alvos
  amada amado amava ambas ambos amiga amigo ampla andam andar andei andem
  andou andre anéis angus ânimo anita anjos anões anote antes anual aonde
  apaga apelo apito apoia apoio árabe arame áreas areia arena ariel arjun
  armar armas armou aroma arroz artes artie asilo assar assim astro ataca
  atena atira atire atiro ativa ativo atrai atrás atriz atual atuar áudio
  aulas autor aveia avião avisa avise aviso azuis bacia bacon bagdá baile
  baita baixa baixe baixo balão balas balde balsa bambu banca banco banda
  bando banho barão barba barco bares barra barro bases basta batem bater
  bates bateu batia batom bebam bebem beber bebês bebeu bebia beija beije
  beijo beira belas belos berço besta bicha bicho bifes bispo blair blefe
  bloco bloom blusa boate boato bobão bobos bocas bolas bolha bolos bolsa
  bolso bomba bônus boone borda bordo botão botar botas botou braço brava
  bravo brega breve brien briga brisa bronx bruta bruto bruxa bruxo buquê
  burra burro busca busco caber cabos cabra caçar caças cafés cagar caiam
  caído caine cairá cairo caixa calar calça caldo calem calma calmo calor
  camas campo canal canoa canos cansa canta cante canto capaz capuz caras
  carga cargo carne caros carro carta casal casam casar casas casca casco
  casei casos casou cauda causa cause cavar ceder cegas cegos celas cenas
  cento cerca cerco certa certo cervo cesta cesto chalé chama chame chamo
  chapa chata chato chave chefe chefs chega chego cheia cheio chico chili
  chora chore choro chove chupa chuta chute chuva ciclo cinco cinto cinza
  circo cisne citar ciúme civil civis clara clare claro clima clipe clive
  close clube cobra cobre cofre cohen coisa colar color comam comem comer
  comeu comia comum conde conta conte conto cópia copos coral corda cores
  coroa corpo corra corre corri corro corta corte corto corvo cosmo costa
  couro coxas credo creio creme criam criar criei crime criou crise cross
  cruel cubra cubro cueca cuida cuide cuido cujas cujos culpa culpe culpo
  culto curar curou curso curta curte curto curva custa custe custo dadas
  dados damas damos danar dança dance danço dando danos daqui darão darei
  darem daria datas davam debra dedão dedos deita deite deixa deixe deixo
  delas deles delta demos dente depor deram derem desça desce desci desde
  dessa desse desta deste deter deusa devem dever deves devia diabo dicas
  dieta digam digas digna digno dirão direi diria disco disse disso disto
  dizem dizer dizes dizia dobra dobre dobro docas doces dodge doida doido
  dólar donos dores doris dorme dormi doses drama dream drive droga dubai
  ducha duelo dupla duplo duque duram durão durar duras durma durmo duros
  durou dúzia edgar elise elite elton elvis encha enche enfia enfie enfim
  então entes entra entre entro envia envie envio épico época erica errar
  errei erros errou ervas espiã esqui essas esses estão estar estas estes
  estou etapa ethel ética euros evans evita evite exame exata exato exige
  exijo êxito expor extra façam facas faces fácil facto fadas faixa falam
  falar falas falei falem falha falou falsa falso falta farão fardo farei
  fargo faria farol farsa farta farto fatal fatia fator fatos favor fazem
  fazer fazes fazia febre fecha feche fecho fedor feias feios feira feita
  feito feixe feliz fêmea fenda fênix ferir feriu feroz ferro festa fezes
  fiada fibra ficam ficar ficha ficou fiéis filha filho filme final finas
  finge fingi finja fiona fique firma firme fitas fizer flora fluxo focar
  fodeu fogão fogem fogos folga folha fomos fones fonte foram força force
  forem forma forno forte fórum fosse foste fotos fraca fraco franz frase
  freio frias frios frita frito fritz frota fruta fruto fuder fugir fugiu
  fujam fumar fundo furar fúria fusão gabar galho gambá games ganha ganhe
  ganho ganso garfo garra gases gasta gasto gatas gates gatos gêmea gêmeo
  genes gênio genro gente geral gerar gesso gesto giles girar girls globo
  gohan golfe golfo golpe gorda gordo gosta goste gosto gotas gozar graça
  grade grama grana grãos grata grato graus grave greer grega grego greve
  gripe grita grite grito grove grupo gueto guiar hades havaí haver havia
  hazel heidi henri herói hilda hogan homem honra horas hotel houve humor
  íamos idade ideal ideia ídolo ienes igual ilhas impor imune índio invés
  irado iriam irmão irmãs irmos itens jaime janta jarra jarro jaula jeans
  jeito joana jogam jogar jogos jogou jogue jóias jonas jovem judas judeu
  judia juíza juízo julga julho julio junho junta junte junto jurar jurei
  juros jurou justa justo jutsu lábio laços laden lados ladra lagoa lagos
  lança lance lápis lares larga largo laser latas latim lavar lavou leais
  leela legal leila leite leito lemon lemos lenço lenda lendo lenha lenta
  lente lento leões lesão leste letal letra levam levar levei levem leves
  levou libra lição licor lidar líder lidou ligam ligar ligou ligue limão
  limpa limpe limpo linda lindo linha linus liras lista litro livra livre
  livro lobos local loira loiro lojas longa longe longo lorde lorna louca
  louco louie lucia lucro lugar luigi lunar lutam lutar lutas lutei lutem
  lutou luvas luzes mabel maçãs macho macia macio madre madri máfia magia
  magra magro maior major malas mamãe manda mande mando manga manhã mania
  manos manto mapas marca marco mares marge margo mario massa matam matar
  matei matem mateo matou maura mcgee média médio medir medos meias meigo
  meios menor menos menta mente menti mesas meses mesma mesmo metal metas
  meter meteu metrô mexam mexer mexeu mídia mijar milão milha milho minas
  minha minta minto missa mitos miúda miúdo moção moças modos moeda molde
  molho monge monta monte moore moral moram moran morar morda morde morei
  morou morra morre morri morro morse morta morte morto mosca motel motim
  motor motos mouse movam móvel movem mover moveu mudam mudar mudei mudou
  muita muito multa múmia mundo muros museu mútuo nação nadar nadia naomi
  nariz nasce nasci naval naves navio negão negar negou negra negro nelas
  neles neném nerds nervo nessa nesse nesta neste netos never névoa niles
  ninho ninja nisso nisto nível nixon nobel nobre noção noite noiva noivo
  nolan nomes norma norte nossa nosso notar notas notei notou novas novos
  nozes nudez nunca nuvem obama óbito obras obter óbvia óbvio ocupa odeia
  odeie odeio odiar odiei odiou oeste olham olhar olhei olhem olhos olhou
  olive ombro omega ondas ontem opção ópera ordem órfão órgão orgia orson
  óssea ossos ótima ótimo ouçam outra outro ouvem ouvia ouvir ouviu pablo
  pacto padre pagam pagar pagas pagos pagou pague paige palco palha palma
  panda paolo papai papel param parar parei parem páreo pares pariu parou
  parta parte parti parto passa passe passo pasta patas pátio patos pausa
  pazes pearl peças pedem pedia pedir pediu pedra pegam pegar pegos pegou
  pegue peido peito peixe pelas peles pelos penal penas pensa pense penso
  pente peraí perca perco perda perde perdi perez perna perto pesar pesca
  pesos peste petra piada piano pilar pilha pinta pinto piper pirar pirou
  pisar pisei pisou pista placa place plano plaza plena pleno pneus pobre
  poção poços podem poder podes podia podre poema poeta polar polvo pombo
  pondo pônei ponha ponho ponta ponte ponto pooja porão porca porco porém
  porta porte porto possa posse posso poste posto pouca pouco poupe pouso
  povos praça praga praia prata prato prazo preço prego presa preso preta
  preto prima prime primo prova prove puder pudim pular pulei pulou pulso
  punho punir puxar puxei puxem puxou quais qualé quase queda queen quero
  quilo ração raças radar rádio rahul raios raiva ramos rampa rapaz rapto
  raras raros ratos raven razão reage reais recém redes redor reese refém
  regra reino renda renee resta resto reúna rever rezar rezei ricas ricos
  rider ridge rifle rindo risco risos ritmo rival river robôs rocha rodar
  rodas rolar rolou roman romeo ronda rosas rossi rosto rotas rouba roube
  roubo roupa rover ruben rufus ruído ruína ruins ruiva ruivo rumor rural
  russa russo sabão sabem saber sabes sabia sábio sabor sacar sacos sacou
  safar saiam saias saiba saída saído sairá salão salas salsa salta salto
  salva salve salvo santa santo sapos saque sarro sasha satan saúde sauna
  seção secar secas secos segue segui seita sejam sejas selar selos selva
  senão sendo senha señor senso senta sente senti sento serão serei serem
  seres seria série sério serra serve servi servo setor sexta sexto shiva
  shore sigam silva sinal sinos sinta sinto sirva sirvo sítio slade sloan
  sobem sobra sobre socar sócia sócio socos sódio sofia sofra sofre sofri
  sofro sogra sogro solar solta solte solto somos sonar sonda sonha sonho
  sonia sopra sopro sorri sorte sótão soube stars steel stein suado suave
  subam subir subiu sueco sugar suíça suíço suíte sujar sujas sujos sumir
  sumiu super supõe supor surda surdo surge surra surto sushi susie susto
  sutiã sutil tábua taças tacos tampa tango tanta tanto tarde taxas tchau
  tédio telas temas temem temer temia temos tempo tenda tende tendo tenha
  tenho tênis tensa tenso tenta tente tento terão terça terço terei terem
  teria termo terno terra tesla tessa testa teste tetas texto tigre times
  tinha tinta tinto tipos tiram tirar tiras tirei tirem tiros tirou titãs
  tiver tocam tocar tocha tocou todas todos tolos tomam tomar tomas tomei
  tomem tomou tonta tonto toque tórax torna torne torno torre torta torto
  tosse total touro trace traço traga trago trair traiu traje trama trará
  trata trate trato trava trenó trens treze tribo trigo troca troco trono
  tropa trote tubos tumba tumor túnel turbo turco turma turnê turno tutor
  ultra úmido unhas união única único unida unido urina ursos usada usado
  usará usava usina úteis útero vacas vácuo vagão vagas valem valer valeu
  valha valia valor valsa vamos vapor vasos vasta vasto vazar vazia vazio
  vazou veado veias vejam velas velha velho veloz vemos vença vence venci
  venda vende vendi vendo venha venho vento vênus verão verde verei verem
  veria verme verso veste vezes viado viaja viajo vício vidas vídeo vidro
  vigia vigie vigor vilão vimos vinci vinda vindo vinha vinho vinte viola
  viram virão virar virei virem viria virou vírus visão visse vista viste
  visto vital viúva vivas vivem viver viveu vivia vivos vocal vocês vodca
  voice volta volte volto vossa vosso votar votos votou vozes zelda zíper
  zonas zumbi
`.trim().split(/\s+/);

/** Só aceitas como chute — nunca viram resposta. */
export const EXTRAS = `
  aadni aalto aamir aarão aaron aarti ábaco abade abafa abafe abala abale
  abalo abana abane abano abata abate abati abdel abdou abdul abeba abeto
  abner abobo abono aboro above abrão abras abres abreu abria abusa abuse
  ácaro acata acato acena acene aceno aceso aches achim ácida acolá acorn
  acton actor actos actua acuda açude acuña acura acuse acuso adair adama
  adami adana adano adare adela adena adere aderi adham adido adiei adiem
  adieu adina adios adiou adira adisa aditi adlai adler adlon adnan adobe
  adoce adoha adore adorn adota adote adoto adria adubo advém advil aécio
  aedes aegis aegon afago afegã afete afiar afina afine afins afobe afoga
  afogo afora after afton afzal again ágata agave ageha ágeis agena agero
  agete agiam agiel agirá agita agite agito agnes agnus agota agree agron
  aguar aguça agudo aguém aguma ahamo ahana ahora ahran ahsha ahtur ahuja
  aiala aicha aidan aider aigoo aimee aimes aioli airai aires aisha aishu
  aitor alada alado alafa alain alais álamo alana alarm alban albee albie
  albin alçar alças alces alceu alcor alden alder aldin aldon alego alejo
  alena alepo aleta alexa alexi alfas alfie alfio alfor algém alger algie
  algoz alguã algun alhos aliar álibe alice alida aliei alina aline aliou
  alisa alise alive almen almir aloha alois aloja alona alone alors alper
  alpes altan altão altea alter alton altro aluga alugo aluro alves alvez
  alvie alvin alvis amagi âmago amaia amais amala amanã amane amani amano
  amará amare amarl amaro amato amazo âmbar amber ambro ameba ameça amena
  ameno ameti amico amida amido amiel amina amine amira amiri amita amnhã
  amoha amola amole amora amore amour amplo amram anais anaju analu anami
  anata ancas anciã andas ander andes andie andor andri andro aneta anexa
  anexo angel anger angie angin angle anglo angor angra anila anima anime
  anina anise aniss anjin anjou anota anoto ansar ansel ânsia anson antar
  antas antía antjr anton antro anula anule anulo anvil anzai anzio anzol
  aorta apago apara apare aparo apear apega apego apela apele apena apgar
  ápice apita apite apoie apolo apraz après april aprox aptas aptos apura
  apure apuro aqaba aquel aquém aquii arado arara arata arato arbie arbor
  arbus arcar arcas arcee archi arcon arcos ardem arden arder ardeu ardia
  ardil ardis ardor ardra árdua árduo areal arfar argel argon argos argus
  arial arian arias árida árido áries arima arion arisa arita aritz ariza
  arlen arles armam arman armei armel armem armen armes armin armor armus
  arnaz arnel arnês arnie arnon arora arpão arque arran arras arren arson
  artem artis artur aruba aruna arvin asada asahi asami asano asger asham
  asher ashes ashur asian aside aslam aslan asnos aspas aspen assai assam
  assan assas assei assis assoa assoe assou aster aston astor astra asuma
  asuna asura ataco atada atado atama atami atari atear ateei ateia ateie
  ateou ateus athar athos ática atice ático átila ative atlas atlee atmos
  atóis átomo atraz átrio atroz atsui atuam atuei atuem atuns atuou atura
  ature aturo audaz auden audie audis audra augie augur aumea auras áurea
  aurel aurus ausem aussi autos avelã ávida ávido ávila avion aviva avner
  avram avril axial axila axton azari azeda azedo ázimo aziza azoto azula
  azuma azumi azura azure azusa babam babão babar babás babel baber babes
  babli bablu babou babur bachi baços baden bader badge badri bafta bagas
  bagel bagos bagre bahar bahia bahts baião baias baila baine bains bajie
  bajor balam balan balco baldi baldo balés balin balon baloo balor balto
  bamba bambi banal bandi bands banes bango bangs banha banhe bania banir
  baniu banjo banoo bansi banta banzé baobá baque baran barbe barbi barbu
  barca barda bardo barfi barge baril barin bário barns baron barre barto
  barts basal basca basco basel basho basia basie basil basin basra bassi
  baste batam batas baths baton batou batra bauer bauji bazán bazar beale
  beals beams beano beans bears beata beate beato beats bebas bebei bebel
  bebum becas becos bedel bedlo beebe beene beeps beera beers began begin
  begum begun behan behar beiço bejan belém belén belga bemis bemol benda
  benes benga benin benji benri benta bente bento benza benzo beque berel
  beria berle berma berna berne berns berra berre berro berta berti berto
  betão betas betel bevan bevin bevis bhanu bhima bhola bhura biagi biasi
  bibas bible bicam bicão bicar bicas bicos bicou biden bielo bifão bigas
  bihar bijan bijou bijuu bilal bilau bilbo biles bilge bílis bimba bimbo
  bimse bindi bindu bingo binta bipar bipei bipes bipou birds birju birra
  bisão bison bites bivas bixel bjorn blade blain blais blame blane blasé
  blaze blefa blefo bless blige blips bliss blitz blogs blore blues blume
  blurr bluto boats bobas bobes bocal bocão bocha boche bócio bocós bodas
  boden bodes bodhi bodie boers boeun bofes bófia bogan bogie bogue bogus
  bohun boiar bóias boies boina boise boite bojan bolan bolão bolar bolei
  bolen boles bolie bolin bolor bolou bolus bombo bombs bonde bondi bondo
  bonds boner bones bongo bongs bonzi bonzo boobs booji boola booms boots
  boovs booze boran bórax borgo borgs borin boris borja borla borns borra
  bosco bosie bóson bossa bosse bosta bosun botam botan botei botem botes
  botha botos botox boudu bovie boxer boxes bozer braba brabo braca brace
  brado braga brahe brain brana brasa brass bratz braun braus brave bream
  breca breda breem breen breja brejo brena breno bretã brian briar brice
  brida bride brigo brion brita brite brito brits broca bromo broom brota
  broto broxa brubs bruce bruhl bruhn bruja brujo bruma bruna bruni bruno
  brute bruun bruza btsix bublé bucal bucha bucho bucum budas budge buena
  bueno bufão bufar bufês bugle bular bulbo buldi bules bulge bulir bulma
  bumbo bunce bunda bunga buona buono bupsi burca burcu buren burgo burla
  burma burns bursa buruu busan busão busta busto butão butim caaba cabal
  cabeã cabem cabia cabin cable cabul cabum caçam cacau cacei cacem cachê
  cacho caçoa caçoe cacos caçou cacto cadão caden cadie cádiz cafer cagam
  cagão cagle cagou cague caiar caias caiba caibo caída caiem caimã caiol
  cairn caite caius cajun calam calão calas calce calço calda calei calha
  calme calos calou calum calva calvi calvo camel cameo campa campi camus
  canaã canan canas cancã candi canga canil canis canja canoe canon canse
  canso capão capar capas capim capra capri capta capte capto cápua cáqui
  caral carão carbo cardo cards cares cárie caril carin cario caris carla
  carli carlo carls carma carme carmo carns carol caron carpa carpe carpo
  carré carte carue casem cases casim casio caspa cassi casta casti casto
  catão catar catco catei cates cathi catie catou catre caule causo cavam
  cavas cavei cavem caven caves cavil cavor cavou ceará cecil cecis cedam
  cedar cedem cedeu cedia cedro ceelo cegam cegar cegou cegue ceifa celal
  celia celie celsa celso celta cemal cemil cenci cenho censo cents cepas
  ceren ceres cerie cerne cerol cerre cerro cerus cerva césar cesca césio
  cessa cesse cetim çetin cetro cetus cezar chaba chabi chaco chade chael
  chaga chaim chain chair chaja chala chams chana chani chano chaos chapo
  chaps charl charm charo charu chase chats chava chavo checa checo cheer
  chefa chege chela chele chels chema cheol cheon chepe chère cheri chess
  chiam chiar chiba chibi chibs chica chidi chien chigs chile china chino
  chiou chips chita chito chivo chizu chloe choca choco chode choji cholo
  choon choos chope chops chose choti chotu choux chova chris chuan chuen
  chuis chuji chujo chula chulé chulo chuma chuni chupe chupo chura chuto
  ciano ciara ciber cidra cielo ciera cifra cílio cindi cindo cinta cipós
  cipri cipro circe cirie cisão cisca cisco cisma cisse cissi cisto citam
  citas citei citou cível clacs claes claim clair clama clame clamo clase
  class claus clava clave clavo clean clear cleon clero clete cleva cleve
  clica clico cline clips clone cloro clubs cmdte coado coagi coala coben
  coble cobri cobro coçam coçar cocas cocei coche cochi cocho cocoa cocos
  coçou codex codis coesa coeso coeur cogan cohan cohle coias coice coifa
  coiro coiso coito colam colas colei colem coles colha colhe colhi colho
  colin colmo cólon colos colou colts colum comas combo combs comeã comei
  comes comin comos comte conan conas cones conga congo conhe conis conor
  conti coors copán copas copie copio copta coque coraã coram coran corão
  corar corça cordo corea corfu corgi corie corja corno coros corou corps
  corsa corso cosas coser cosia cosme cospe coste cotas coube coupe couve
  covas coven cover covil coxia coxos cozer crabs craca crain crais crale
  crane craps crate crava crave cravo craze cream creel creem crees creia
  creon crepe creso creta crian crias criem cries crina crips criss crivo
  croce crocs crohn croix cromo crone crono crore cruas crude cruza cruze
  cruzo cuban cubas cubos cuchi cucos cuias culta cumes cunha cunho cuore
  cupim cupom curam curas curda curdo curei curem cúria curie curro cursa
  curse curti curve curvo cusão cusco cuspa cuspe cuspi cuspo cutie cuvee
  cuzão cuzco daboo dacia dador daens daesu dafna dafne dafoe dagan dagda
  dagen dagon dágua dagur daigo daite daito dalai dalal dales dalia dalma
  dalva damar damen dames damiz damji damon dândi danem danes danil danjo
  danou danse dante danza danzo daora darás darci dardo daren dares darin
  dario darla darma darou darpa darro darui dasan dasha dashi datam datar
  davaï daves davie davin davis davor davos daxam deana deane deano deans
  deare débil débis decai décio decir dedal dedar dedou deduz deeds deena
  deepa deepu deere deets defoe degan degas degra deion deito deitz deleo
  delgo delhi delia delma delon delos demão dembe demir demon dende dendi
  denim denis deniz denon densa denso dento depõe depôs deprê depto deque
  deran dereo deres derme deron dersu desai desço desna despe despi detém
  deteu detox deuce devam devas deven deveu devil devin devir devoe devon
  dhabi dhara dhari dhoom dhoti diaba diana diane dicen diego diehl dietz
  digne dijon dildo dileo dilma dilui dimas dimeo dimon dinar dinda diner
  dingo dings dinho dinis diniz dinos diodo diogo dione diore diosa dique
  dirás dirce disca diser dispa dispo ditam ditar ditas ditei ditos ditou
  divas diver dixie dixon dizei doada doado doane doará doava dobel dobie
  doble dócil dodee dodie dodói doerá doesn dogen dogma dogon dogue doíam
  doina dolan dolce dolor domar domei domir domos domou donal donas donde
  dondo dongs donie doone doors doose dopar dopou doque doral doran doren
  doria dorie dorio dorje dorma dorne doron dorri dorsa dorso dosar doshi
  dosso dotes dotou douce doula dover dozen dozer draal draco draga drago
  drags drazi drena drene dreno dress driba dries drina driss drogo drona
  drone drool drope dropo drops drove druce drugs drums drune druse druso
  duane dúbia dúbio dubla dublê duche ducor ducos ducto dudes duela duele
  dueto dugan dulce duman dumar dumas dumbo dunas dunes dunga dúnia duomo
  duper dupin dupré duran durei durem durer durex durga durin durmi duron
  dusan dutos dutra duval eadie eagan eager eagle eames eamon earle earls
  earps eason eaton ébano ebola eboni ébrio ecoam ecoar ecoou edema edges
  edina édipo edita edite edito edlee edsel edson educa educo eesha éfeso
  efrem efron égide egito éguas ehome ehren eiger eigil eiiie eilis einar
  eisen eixos ejeta ejete elajá elana elden elder eldon elege elegi elejá
  elena eleni eleva eleve elevo elfie elfos elgar elgin elian elias elina
  elisa eliza elmer elmos elora elsie elura elvin elzar email emana ember
  emeli emese emile emine emiri emita emite emiti emito emoji emori enchi
  encho encom ender endor endre endro eneas enema enfio engel engle enjoa
  enjoe enjôo enlai enlil enoja enojo enola enron ensor entar enten enter
  entoa enver enxer ephra épica epóxi epsom epson equal equis equus ereta
  ereto ergam ergue ergui erina erler ernie erram errem erres errol error
  ervin esben escoa eshan eshel eslam esopo esotu espen esper espie espio
  essam essen essex essie esssa essse estam están esten ester estos estpa
  estra estva esvai ethan ethne ethos ético etnia etore eudes eugen euler
  eurus evers evgin evian evito evoca exala exale excel exeto exiba exibe
  exibi exibo exigi exigo exija exile exime exite êxodo expõe expôs expus
  faber fabia fabio fabre fabri facão facer facho facts facul fades fados
  fagan fagin fagon fahim faire faiza falai falan falco fales falhe falho
  falir faliu false falte falto famos fando fania fanta fante faram farás
  farça farda fares farge faris farms farpa farra farsi farva fases fassl
  fatie fatma fatou fatso fátuo fauji fauna fauno faure fauzi favas favos
  favre faxes fazei fazen fazio fears febem fecal fedem feder fedeu fedex
  fedia fedra feeds feels féfis felis felix felps feltz fêmur fence fendi
  fenol fente feras ferem feria fermi feron ferra ferre ferva ferve fervi
  fervo fetal fetos feudo fever fevre fiado fiapo ficai ficas fiche ficus
  fidel fieri fiero figas figos filão filar filas filer filés filii filma
  filmo films finca finda finis finjo finos finta fiofó fiora fiore fiori
  firam fires firpo fisco fisga fisio fitar fiver fives fixam fixar fixas
  fixei fixem fixer fixes fixos fixou fizbo flaca flaco flags flair flama
  flame flaps flare flass flats fleur flies flite floco floor flore flori
  floro floss fluam fluem fluía fluir fluiu flúor fobia focal focam focas
  focos focou focus fodam fodão fodas fodem foder fodia foehn fofas fofos
  fogel foges fogle foice foles folgo folia folie fomes fonda fonso foods
  fools foote foque forão foras forço fords fores forge forja forli forme
  formo foros forra forro forza fosca fosco fossa fosso fóton fours frade
  fraga frain frame frane frans frapê frear freda fredi fredo freds freei
  freel freia freie freja freon freou frère frete friar frica frida fries
  friis frisa friso frite frits frode frodo frome fuçar fuças fucei fuchs
  fuçou fudeu fudge fuego fuera fugas fugaz fugia füher fujão fujas fujii
  fujio fujir fulci fumam fumas fumei fumem fumio fumos fumou funda funde
  fundi funes funga fungo funil furam furão furei furem furio furor furos
  furou furta furto fusca fusco fusil fusos fútil futon fuzil fuzis fuzuê
  gaara gabam gabão gabei gabim gable gabon gabor gabou gacha gadge gados
  gaeta gafes gagin gagos gaita gaius gajas gajni gajos galan galão galãs
  galba galen gales galgo gália gálio galos galra gamal gamão gambé gamer
  ganem ganga gangs ganja ganma ganon gansa gantu gantz garbo garça garda
  garde garis garma garoa garza gaspa gasps gaste gatão gator gauge gaura
  gauri gauss gávea gavel gavin gazer gazes gazua geada gears geena geeta
  geils geirr geiss geito gelar gelei gelos gelou gemas gemem gemer gemeu
  gemia genda genei gênia genie genii genin genji genma genoa genos genta
  geram gerbo gerda gerei gerem geria gerir germa germe germs gerou gerra
  gerri gerta geste ghani ghazi ghoul giada giana gibão gibis gifts gigas
  giger gigio gigli gilda gilou gimli ginga ginge ginsu ginza gioia giram
  giras girei girem gíria giron giros girou gitmo given gives givin gizmo
  glacê glade glass gleba gleen glide globe gloss glove gmail gnome gnomo
  gödel godos goela goetz gogol goiva gojun golan golas golda goldi golem
  goles golos gomas gomen gomer gomes gomez gomie gomos gondo gongo gonza
  gonzo goode goose gopal gopro goran goren gorge gorgo gorpo gorro gosei
  gosha gosma goten gotha gothi gouda gozam gozei gozem gozes gozou graal
  grace graco grado grail grape grass grava gravo graxa grazi grear grebs
  greco green grelo greta grete gretl grier grife grifo grila grilo grits
  grohl groom grose gross grous gruas gruda grude gruen grune gruta guana
  guano guans guapo guera guero guess guiam guião guias guicn guida guide
  guido guiei guiem guila guile guiné guiou guise guito guizo gülen gumbo
  gumes gunga gungi gunjo gupta guran guria guris gurus gusta gusti gusto
  guten haase haber habia hábil habla hablo hacer haces hacha hache hachi
  hadar haden hader hadji hafiz hagan hagar hagen hager hagia hague haifa
  haiga haile haise haiti hajam hajis hajra halal halen hales halil halim
  halon halos hamal hamam haman hamar hamas hamdi hamel hamer hamil hamre
  hamza hands hanes hania hanim hanin hanói hansi hantz hanzo haole haram
  haran haras harém haris harms harpa harpo harri harte harts hartz harue
  harum harun haruo harus harve hasan hashi hasil hasim hasso hasta haste
  hater hates hatsu hauen hauer hauru haute havel haven havin havre hazen
  heads hearn heave hebdo heber heche hecho hedge heels hegel heide heigl
  heine heini heinz heiss heitz helen helga helge helgi hélio helix helms
  henan henge heras herda herde herne heron herta hertz hervé herzl hesam
  hesse hesus hetal heure hexam hiato hideo hides hidra hidro hiena hífen
  hijos hilde hilts himba hímen hindi hindu hines hinos hiper hirai hiram
  hiroi hisao histã hiten hiura hjelm hobie hocus hodes hodge hodja hodor
  hofer hogue hohne holds holes holtz homen homer homes homie homos homus
  honda hondo honor honre honro honus hooda hoodz hooli hoops hopes horan
  horda horne horns horse horta horto hórus hoshi hosni hours house hover
  hrafn hsiao hsien huber hubie hulda hulen hulme human húmus hunan hunos
  hunte hunts huron hurra hurts hutus iacon iagom ialta iancu ianto iaque
  iates ibama ibiza iblis ibope ibsen içada içado ícaro ícone idaho idgie
  idias idols idona idosa idoso idota idris iêmen iglus ignis ilana ilene
  ilesa ileso ilija ilona ilson iluda ilude iludi iludo image imame imani
  imara imita imite imito imola ímpar ímpia ímpio impõe impôs impus imram
  imran inala inale inara inari inata inato incas incha inder index índia
  indie indra indri induz infla infle infra ingar ingel inger inibe inigo
  injun inman inori inoue insta intel inter intra intro invéz iogue ioiôs
  iolco ipads ipeca ipods iqbal irada ireis irena irene ireru irfan irgun
  irias irina irisa irons irvin isami isamu iscas ishan ishbo ishii ishta
  islam islão isler isles ismos isogi isola isole issho issso issue istmo
  ítaca italo itami itara ivana ivano ivanz ivers ivete ivone ixion izmir
  izumi izumo jaana jaane jabez jacas jacee jacto jaden jadon jadoo jafar
  jagan jäger jahan jahel jahil jairo jalal jalan jalen jalil jalue jamal
  jamar jamba jambo jamel james jamie jamil jamis jamon janae janai janel
  janes jango janie jânio janis janja janos jante janto janus japan japão
  japas jaque jarda jaris jarle jarno jasão jasna jason jassa jassi jatin
  jatos jaume jaune javor jaxon jazem jazer jazia jeane jebel jedis jeeps
  jeetu jefra jegue jehan jejua jejum jelco jenga jenin jeová jerez jerri
  jessa jesse jessi jesus jeter jibun jidai jigar jimal jimbo jinbo jingo
  jingu jinxi jipes jitsu joabe joans jobim joder jodie jogão jogas johan
  johar johns johri joice jolie jompa jones jonjo jonze joran jordi jorex
  jorge jorra jorro joshi josie jossi josué jovan joven joxer jozea józsi
  juana juani jubal jubei judea judex judge jugar juhee juice jules julgo
  julia julie jumba jumbo junco junge junie junio junon jupie juram juran
  juras jurem júris jussi juste juubi laban label lábia labor lacan laçar
  laçou lacre ladon ladoo ladre lager laico laida laila laine lajes lajos
  lalau lamar lamas lamba lambe lambi lambo lamen lamia lampe lanai lanço
  landa lando lands lanes lange lanie lanto lantz lanza laoer lapão lapin
  lapso laquê larbi large lariê laris larra larri larue larus larva lasca
  lasix lassa lasse lassi lasts latão latem later látex latia latin latir
  latiu lauda laude laudo lauer laura laure lauri lauro lause laval lavam
  lavas lavei lavem lavin lavon lavra laxmi lazar lazer lazio lazlo ldade
  leads leafs leana learn leave lebel lebre leche ledge ledom leeds leena
  leeta leeza legar legba leger legos legou légua leiam leias leica leiga
  leigo leiva leléu lelia leman lemas lemes lenga lenin lenon lenor lenox
  lentz leoas leola leona leone leoni leora lepel lepra leque leram lerão
  lerda lerdo lerei lerem leria lerma lesli lesma lesra lessa lesse letão
  letha lethe levai levan levas level lever levin levis levon lexie lexus
  lgual lhama lhasa liana liane liars liber líbia líbio libre liceu lidam
  lidas lidei lidem lidia lidos liebe liège liesl ligas lígia ligre lilás
  lilia lilix lilja limar limas limbo limón limos lince linde linds linea
  lines lineu linge lingo linho linux lions lírio lisas lisos lissa lissi
  liste listo lítio liuba liuer livan lives livia livie livin lívio lixão
  lixar lixas lixei lixem lixos lixou lndia lobas loção locar locos locus
  loder lodge lofts logan logar login logon logos logou logro logue lohan
  loiça lóide loire lojor loman lomas lomax lombo lomis lonas londo lonzo
  looma loops loose lopes lopez loras lorax lorca lords loren lorie lorin
  loris lorne lorre loser lotam lotan lotar lotes lotia lotor lotou lotso
  lótus louis louna loura louro lousa loute louva louve louvo lover loves
  lovin lrmão luamz luana lubas lubin lucan lucas lucha luchi lucho luchs
  lucie lucio lucra lucre ludie ludus luego lufer luger luhca luisa luise
  luiza lujan lulas lumen lumes lunes luntz lupas luper lupin lúpus luque
  lurie lutan lutie luton luxor luxos luzia luzon maari maati mable macao
  macau macer macha machê machi machu maçom macon maços macro madam madan
  madea madge madhi madhu madou madox maeda maeve magda magee magie magma
  magna magne magno magoa magoe magoo magos magua magus mahal mahdi maher
  maheu mahir maias maida maids maier maile mails maine mainz maiôs maíra
  maire maite majin majnu malee males malha malho malia malin malmö malon
  malou malta malte malum malva malvo maman mamão mamar mamas mamba mambo
  mamie mamou manas manca mance manco mandi mands manés mange mango mangu
  manhê manja manjo manju manoa manon manor mansa mansi manso manta manti
  manus maomé maori mapes maple maqui maras marce marci marda mardi maren
  marfa marga maria marie marin marir maris mariz marja marla marle marlo
  marmo marna marne marni maron marra marta marte marti martz marui marva
  masai masao masca masco masen maseo maser masha masjá mason masra masri
  massi massu masti masuo matan matas mater mates matin matiz matoi matos
  matru matsu matzá matzo maude mauer maule mauli mauna mauri mauro maven
  mavis maxie maxim mazal mazar mazas mazda mazel mazie mazlo mazur mcaio
  mcfee mcrae mcvie meada meade means meara mears meaux mecha meche medea
  medel medem medhi mediu meelo meena meenu meera meers meese meeta meets
  megan megha mehar mehdi meher mehor mehra mehta meier meiga meiji meilu
  meine mejia mejor melão melar melas melba melea melho melia melon melou
  melro melun memes memso menem menlo menma menon mensa mento menus meral
  meras mercê merci merda merde merel merle merlí meros merri mertz messe
  messi messr metam metem metes metia metil metin meuse mexas mexem mexia
  miado miami miata micha michê michi micol micos micro midas midge mieta
  mieze migra mihai mihir mijam mijão mijei mijem mijou milan milas miles
  milne milos milou mimam mimar mimei mimos mimou minam minar minds miner
  mingo minho minis minor minos minou mintz minus miojo miolo míope mirae
  mirai miral miram mirar miras mirco mirei mirem miria mirim mirna miron
  mirou mirra mirre mirta mirza misha mismo missi missô mista misto miter
  mitia mitra mitre mitsu mitzi miura mixar mixer mizar mizer mneme moabe
  moana mobil mocha mochi mocho moços modas model modem modus moela moema
  moeru mofar mogli mogno mogol mogul mohan mohei mohel mohie moída moído
  moira moïse moita molar molas molda moles molha molhe molto momon monde
  mondo monga mongo monix monja monje monro monti monto montu monza moone
  moons moors moose moras morbo mordi mordo morel morem mores morfo moria
  morin mormo morna morno moroi moron moros morsa morsi moser moses mosha
  moshe moshi mossa mossi mosto mosul motas motoi mouna moura mouro mousa
  movas moves movia movie movin moxam moxie moxon mozão mozar mucha mucho
  mudas mudem mudes mudez mudge mudon mudos mufti mugen mugir muher mujer
  mulan mulas multe multi multo mumbo munda mundi muñez munga mungo munir
  muniz munoz munro muntz murai mural murli muroi murro murta musas musgo
  mushi mushu musse musso mutar muten mútua nããão naama nããoo nabil naboo
  nabos nachi nacho nacio nadal nadam nadas nadei nadem nader nadie nadim
  nadir nadja nadji nadou naeha nafta nagai nagar nagel nagin nagle nagre
  nagus nahum naidu nails naima naina naipe nairn naito najla naldo naman
  names namie namin nanar nanbu nance nanda nandi nando nandu nanga nante
  nanto nãooo naota naoto narco nardi nardo naren narim narns narra narvo
  nasal nasan nasça naser nasim nasir nasse natal natan natas natha natia
  natos natsu nauer navas navel navin nazar nazca nazim nazir nazis ndutu
  neale neals nebel necas nedra needs neela neeli neelu neema neena neesa
  neeta neetu neeva negai negal negam negan negas negos negue nehru nehum
  neils nelda neman nenum nepal nerio nerva nerve netan netas neton netsu
  neuro nevar neves nevin nevou nexus nicho nidal niebo niels nieto nieve
  nigel níger nihal nihao niies nilaa nimon nimue ninar niner ninfa ninfo
  ninon niños niobe nique nisha nishi nisse nitin nitro nivea niven niver
  nives nizam nobis noble nobuo noche nódoa nodos noéis noemi noire noise
  noita nolte nomar noona noora noras norbs norbu norco norén norge noris
  noron nosos notam notem notes notre noura novel noves novus noxon ntoni
  nuala núbia núbio nudes nudge nueva nuevo nuito nulas nulos numan numas
  nunes nuñez nuria nurse nutre nutro nvocê oásis oates obaba obara obesa
  obeso oblio oboro obree obtém ocaso ocean ochio ochoa ocupe ocupo odeon
  odile ódios odone often ofthe ofurô ogami ogata ogden ogiva ogres ogros
  ohana ohara oharu ohisa oiçam oishi oitos ojogo ojuiz ojúri olááá olden
  older olena óleos olhai olhas olhes oliva olmos olsen olson omaha omita
  omite omiti omnes omnia omnis omori omura onari onças onion onler onoda
  oogie oompa ooops opaca opaco opala opale opere opero ophir opina opino
  opõem oporá optam optar optei optou orado orais orava orbes orcas orcem
  orden order oreal oreos órfãs orfeu orhan oriel oriol orion orlas orlin
  orman ormuz ororo orrie orrin ortho ortiz orton orval orvil osage osama
  osamu oscar osela oshin osman osmar osore ósseo ossie osten oster ostia
  ostra osugi otani otcho otelo otero oteru other ótica ótico otite otomo
  otoms otona otoni ouças ouija ouros ousam ousar ousas ousei ousem ousou
  outer outis ouver ouves ouvis ovais overs ovnis óvulo oxalá oxfam óxido
  ozgur ozone paavo pacal pacas pacer pacha pache pachi pacho padma padmé
  pádua pagan pagão pager paglu paije paine pains paiol paira pairo paisa
  paise paiva pajem palas palau paleo palin palio palme palmo palms palos
  paltz pampa pança panco pande pandi pando pandu panem panes panis panos
  panta pants panza paola paoli papal papão papar papas papen paper papos
  papua paqui paraa parai paras parça parce parco parda pardo párea pargo
  pária parir paris parle parlo parma parra parsa parsi parts parva parvo
  pasar pasco paseo pasha pasma pasmo pasto patel pater patil patim patna
  paton patou patri paula pauli paulo pauls pause pauta paval pavão pavel
  pavia pavio pavor pavri paxil pdvsa peace peale pease peçam pecan pecar
  pecos pecou pedal peder pedes pedis pedro peeps peeta pegas peida peide
  pelar pelve pemba penar penca pence pende penge pênis peões peola pepel
  pepes pepsi pepto peque peraê peras perce perdo peres perla perón perri
  perro persa perua perus pesam pesce pesci pesco pesei pesou pessa pesso
  pesto petal petar petco peter petie petri petro pétur pezão pezoo phase
  phile philo phlox phnom phone photo phrae piama picam picar picas picha
  piche picon picos picou pidão pidge piece piero piers pietà pifar pifou
  pilão pilas piles pimba pinça pince pinel pines pinga pingo pinha pinho
  pinos pinte piora piore piotr pipas pipes pique piram pirão piras pirei
  pires piron pirro pisam pisca pisco pisem pismo pisos piter píton pitou
  pixar pixel pixie plaga plain plame plana plane plans plata plate platô
  platz plebe plexo plugs pluma plume pluto poças pochê pocus podar pódio
  podou pogue poins polca polda poldi pólen polia pólio polir polis poliu
  pólos polpa polui pomar pomba pomos pompa ponce ponde pondi ponds pongo
  ponti ponzi ponzu poofs poole poona popas popol poque porei porel pores
  poria pornô poros porra porre posam posar posei posen poser poses posou
  posta posts potes potra potro potus poupa poupo pousa pouse povão prada
  prado prana praxe prece preda prega press prevê previ preza preze prezo
  priam price pride prien prinz prion prior prisã prism priss prius priva
  prive prize probe profa profe prole promo prosa proto provo prumo prune
  psico ptera púbis puchi pudia pudor puede puedo pufes pugin pujol pulam
  pulao pulem pulga pulha pulis pulos pulpo pulsa pulse pumas pumba punam
  punem punha punia puniu punta punto puras purga purim puros pusan puser
  putão putas putin putos puxam puxão qadir qadri qaeda qandi qapla qarlo
  qasim qatar qilin qohen quado quail quano quasi quati queca queer quejá
  quele quepe quere queri queso queta quiçá quién quimo quina quipá quite
  quito qumar quota raava raber rabin rabos racer races racha rache racho
  rader radha radhe radin radon raees rafer ragan rager raghu rahim raiar
  raias rails raims raina raine rains raiou raisa raise raita raito raizo
  rajan rajni ralar ralei rales ralha ralho ralis ralos ralou ramal raman
  ramas rambo ramen ramon ramse ramus rance ranço randa randi rando rands
  range rango ranho ranma raoul rapar rapel rapha rapta rasas rasca rasen
  rasga rasgo rasha rasos raspa raspe raspo rasta rasto ratan ratão ratas
  ratel raton ratso ravan ravel raves razer razia razor rcito reade reagi
  reaja reajo reale realm reata rebel recai recon recta recua recue recuo
  rédea reduz reece reema reems reena reeve refaz refez refil refis refiz
  refri regal regam regan regar regem reger régia régio regis regou régua
  regue rehan reign reiji reims reina reine reiss relax reler reles reluz
  relva remar remem remer remix remos remou remus remzi renae renal renan
  renas rende rendi rendo renie renji renta rente renzo repõe repor repôs
  reses reste retal retas retém reter retos retrô reúne reuni reúno reven
  revés revie reviu revue rexie rezam rezas rezem rezou rhade rheda rhine
  rhino rhoda rhode rhona rhone riais riana riano richa riche ridaa rifas
  rigel rigor riina rijos riles rimam rimar rimas rímel rimes rimos rimou
  ringo rings rinha rinri rinse rioja ripas ripon riram rirão rirei rirem
  riria risca rises risha rishi risse riste riton ritos rivas rixas rizvi
  roads robes robie robin robou robur roçar roças roche rocío roçou rodam
  rodan rodei rodel rodem roden rodeo rodes rodge ródia rodin rodou rogai
  rogan rogar rogen roger rogis rogou rogue rohan rohde roída roído rojão
  rojas rojos rolam rolas rolei rolem rolex rolfe rolha rolos romãs romba
  rombo romer romeu rompa rompe rompi ronan ronca ronco ronde rondo ronee
  ronin ronon rooms roopa roosa roose roots roper roque rosca rosco rosen
  roses roshi rosie rosna rosne rossa rosso rotor rouca rouco rouen rouge
  route roxas roxie roxor roxos rozan rozen rubel rubem ruber rubin rubio
  rubis rublo rubor rubra rubro rudes rudge rudin rudra ruela rufar rufem
  rúfio rugal rugas rúgbi rugem ruger rugia rugir rugiu ruler rules rumam
  rumar rumba rumbo rumos rumou rumpo runas rupal rúpia rusga russe rüstü
  ruxin saami saara saban sabei saben sabin sable sabra sabre sabri sacam
  sacas sacha sachê sachi sachs sacia sacie sacra sacré sacro sadan sadhu
  sadia sadie sadio safam safei safem safia safou safra sagan sagar sagas
  sagaz sager sahai sahar sahel sahil sahir saidi saiem saigo saijo sails
  saito sajhë salam saldo salem sales salga salia salim salma salmo salon
  salte salvi samar samba sambo samia samir samoa samos sampo samra sanaa
  sanae sanam sanar sande sandi sando sands sandu sanga sange sango sanha
  sania sanja sanji sanju sanma sansa santé santi saori sapna sarai saram
  saran sarar sarau sarça sarda sardi sardo sardu saree sarge sarin saris
  sarja sarna sarni sarno saroo sarou sarti sashi satar satie satin satis
  satou satso satur sauce saúda saúdo sauer saulo savan saver saves savio
  saxão saxon scala scans scare scarn scars scavo scene schön schue scion
  scola scone scopa score scram scrum scuba scusi seale seals sears sebas
  sebes secam secor secou sedan sedar sedas sedei seder sedes sedex sedou
  seduz seeds seein seela seele seema seems seeta segal segan seger seher
  seiji seine seios seiva seixo selas selei selem selim selin selma selou
  sêmem sêmen senda sengi senho senil senis senju sense senzu seoul sépia
  sepse septo seque seram serás serge sergi sergo serle serre sérum serva
  sessx sesta setas setes sethe sethi seton seuss seven sever sexos shada
  shade shado shafe shain shale shalu shama shame shamu shana shane shani
  shano shape shara share shari shaun shave sheas sheba sheen sheer shehu
  shere sheri sherm sheru shiar shiba shido shifu shige shilo shima shina
  shine shino shion ships shira shire shirl shiro shita shite shive shivi
  shizu shoes shoji shona shops shota shoto shots shove shran shugs shuji
  shula shura shuri shute sibel sidao sidhu sidle sidon sidos sidra siege
  siena sifão sigas sighs sigla sigma signe signo siham siiim silas siler
  sílex silje silos silvo silvz simão simar simba simca símia símio simla
  simon sinai sinan since sindo singe sings sinha sinhô sinti sinur sinus
  sioux sipes siras siren síria sírio siris sisos sissi sites situa sivan
  sixto slate slava slave slean slghs slice slide slime slope slote slots
  slurm smael smear smile smits smuts snape snaps sneha snipe soado soará
  soava sobel sober socal socha sochi socou sodan sodas sodom sofás sofer
  sofie sofus soham solal solan solas solda soldo soler soles solha solis
  solon solos solus somam somar somas somei somem somer somji somou sonal
  sonam sonde songs sonhe sonja sonos sonsa sonso sooni sopão sopas sopre
  soque sorbo sordi sordo sorel soren sorgo soria soros sorta sósia souci
  souls souma sousa sousè souto souza soval sovar sozin space spade spago
  spain spano spanx spare spats spear specs speer spica spice spies spiga
  spira spiro spitz spode spoon spots spree spuds spurs squiz srtas stace
  staci stade stage stahl stahr stain stane stans stare starm starr stasi
  state stats stavo steal steam steen steps stern steve stevi stevo stijn
  stina stine stipe stiva stole stoli stolz stone stops store storm strax
  strix strom strum studs stuie stupa sturm stutz suada suava subia sucio
  sucos sucre sudão suder sudha sueca suede sufis suflê sugai sugam suger
  sugou sugue suhan suína suíno suits sujam sujan sujei sujem sujou sulco
  sulfa sumam suman sumer sumia sumos sunee sunga sunil sunpu supôs supra
  supre supus suren surfa surfe surfo surgi surja surta surte susan sussa
  sussu sutis sutra suvla suzan suzie svein sveta szabo szeto szura taani
  taber table taboo tabor tabus tacar tacha tachi tacho tacou tadao tadeo
  tadeu taéis taels tahan tahir tahna tahoe tahta taiga taiji tails taipé
  taira taiti talan talão talar talas talco tales talha talho talia tálio
  talma talon talos talus talve tamal tamao tamar tambã tambo tamil tamir
  tamos tampe tampo tamra tanas tanaz tanba tanco tandi tando tanga tange
  tania tanis tanja tante tanvi tapar tapas tapei tapem tapes tapia tapou
  taque taran taras tarda targa tarin tarja taron tarso tarte tarts tarun
  tarzo tasca taser tasha tashi taste tatem tater tates tatia tátil tatin
  tatoe tatom tatoo tatsu tatua tatue tatum tatus taupe tauri tavam tavde
  tavez tavon tavor tavua taxar táxis tazer tazos tchan tears tease tebas
  tecem tecer teceu tecla tecle tecno tecto tecum teela teena teens teerã
  tegan tegel tegui teias teima teixo tejas telão telex telha telma telmo
  telos temam tembo temes temeu têmis temor tempe temps tenar tenaz tendu
  tener tenez tenga tengo tengu tênia tenma tenor tenra tenro tense tênue
  tepes teram terás teres terje terna terre terri terzi tesão tesco teses
  teseu testo tétis teton tetos tetra tetro tetsu tevin texas thabo thais
  thals thane thapa thatâ theda theia their theme theon thera there these
  theta thiel thieu thora thorn those three thugs thule tiago tiana tiara
  tíbia tibor tibre ticar tidal tidas tidos tiene tiete tifón tiger tigna
  tihar tilda tilde tília timão timbo timer timex timon timor timos timur
  tiner tinga tinge tingi tinho tinir tinja tinle tique tirai tires tirza
  tisbe tisha titan titia titio title titor titus tizia tobei tobel tober
  tobin tobor tocas tocos todor togar togas tohno toine tolas tolba toldo
  tolha tolin tomai tomaz tomba tombo tombs tomes tomin tomoe tomos tonar
  tonda tonde tonel toner tonga tongo tongs tonha tonho tonia tonie tonin
  tonio tonje tônus toole tools tooms tooni toots topam topar topas topaz
  topei topos topou toras torça torce torci torço tordo torgo tório toros
  torpe torra torro torso torus tosca tosco toshi tossi totem totós touca
  touie touji toula tours touxe tovar toxie tozan traça traci trade traem
  trags traia trail train traio trans trapo trave travo treco trees trejo
  trela trema treme tremi tremo trena trepa trepe trepo treta treva trevi
  trevo trial tribe tricô trier trife trina trine trini trino trion trios
  tripa tripé trips trism triva tróia trois troma trova troxe truco trude
  trudi trufa trupe truro truss truta tsoul tsuba tsuda tsuge tsugi tsuru
  tubal tubas tudor tudos tufão tufos tufts tuhon tuíte túlio tulpa tulsa
  tulse tulsi tulum tumos tunde tuner tunes tunis turan turba turca turfa
  turfe turim turin turns turva turvo tussa tusso tutsi tutus tuula tuunz
  tuvia uaiii uando uanti uauuu úbere uchoa udara ufano uhara uhura uhuuu
  uivam uivar uivos uivou ulhão ulnar uluru umami umber úmero úmida umrao
  unção uncas uncle under ungar unger unges ungir ungiu uniam union unirá
  unmei unpei unser untar until upolu upton urais urano urban uréia urgir
  urias uribe úrico uriel urine urino urnas urros ursão ursua ursus urubu
  urvil urzes usagi usain uschi usher usman usual usura utamu uther utica
  útima útimo utrom úvula vaasu vaatu vachs vadão vader vadia vadim vadio
  vadis vagal vagam vagar vagem vagos vagou vague vahue vaiam vaiar vaias
  vaiou vajra valar valas valda valde valen vales valho valis value valva
  vamor vamso vance vanda vande vando vânia vanja vanos varal varan varão
  varar varas varda vares varga vargo varia varie varla varma varna varni
  varno varou varra varre varri varro varun varus vasco vasso vasti vatel
  vause vazam vazão vazei vazem veces vedar vedas vedes vedra veena veera
  veeru vegan vegas veios vejas velar veles velez velma velva venal venço
  venga vênia venom venta venti verás verax verba verbo verda verdi veres
  verga verge verma verna verne versa verta verte verve vesga vesgo vespa
  vesse vesta vesti vetar vetei vetor vetos vetou veuve vhari viaje vibes
  vibha vibra vibre vibro vices vicia vidal vidão vidar videl vidia vidor
  vieja viejo viela viena viene viens viera viets vieux vigas vigio vilas
  vilde vilma vilna vimal vince vinco vinde vines vinga vingo vinil vinis
  viole viper viral virás viren vires virge virgo viril viris visam visar
  visco visgo vishi visom vison visor vitae vitam vitor vitro vitus viúvo
  vivam vivar vivaz vives vivir vivis vivre vixen vizir vlada vlade vlado
  voado voará voava vocêi vocêm vodoo vogal vogel vogue voilà vojta vôlei
  volga volos volpe volts volvo vonda voraz voros vorta vorus votam votan
  votei votem votre vovós vrata vries vroom vulgo vulto vulva xaile xales
  xamãs xampu xanas xanax xangô xelim xenia xenon xenos xeque xerez xerox
  xever xhosa xiita xindi xinga xingo xisto xogum xtina xviii zaara zabar
  zabel zadie zafar zafer zagor zahir zahra zaire zaius zalto zaman zamir
  zampa zanga zango zanon zaofu zarbi zarpa zarra zarre zebra zeena zegna
  zehra zeiss zelar zelos zenas zenda zendo zenon zeons zerar zerei zeren
  zeros zerou zetas zetsu zhaan zhuge zimba zinco zinho zoada zoado zoava
  zobar zofia zohan zohar zohra zoila zomba zombe zombo zonda zonza zonzo
  zoome zooni zoran zorba zords zorin zorra zorro zosia zouri zuado zuber
  zubin zuera zughi zulfi zulus zumba zumbe zunir zupan zushi
`.trim().split(/\s+/);

/** O dicionário de aceitação: tudo que pode ser digitado, na forma sem acento. */
export const ACEITAS = new Set([...RESPOSTAS, ...EXTRAS].map(semAcento));
